### ISSUE TITLE
ad ctrl-l ketboaed shortcut to bash and zsh in config by default.

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantOS#10]
ad ctrl-l ketboaed shortcut to bash and zsh in config by default.

in zsh its 
`bind C-l clear`
in key-bindings.zsh

**Comment by paperbenni** [comment]
Zsh already has that preconfigured. Bash is in vim mode by default, you can press escape to go into normal mode and then press ctrl-l

**Comment by NicTanghe** [comment]
weird it diden't work on my Zsh before i added it.
in bash it was working tho and i dident change anything. Odd
