### ISSUE TITLE
Calculator application

### ISSUE THREAD

**Issue by Cole320** [instantOS/instantOS#101]
It would be really nice to be able to run calculations straight from the instant launcher, and then copy them to your clipboard after.
Something similar to [this](https://gfycat.com/sociabledopeyherald-unixporn-linux).

**Comment by con-f-use** [comment]
The <kbd>k</kbd> <kbd>c</kbd> instant assist (<kbd>Super</kbd> + <kbd>a</kbd>) provides a calculator. To build that into the launcher would be confusing (no pun intended) and clash with it's functionality - also people don't calculate that often.

**Comment by Cole320** [comment]
I actually really like the idea of a built in syntax, I might set that up on my own install.
