### ISSUE TITLE
[Feature request?] Right mouse click to close app windows open on the task bar

### ISSUE THREAD

**Issue by marek-lach** [instantOS/instantOS#11]
When an application window is open, it could be that by right-clicking with the mouse onto the window in the taskbar one could select `Close`.

**Comment by paperbenni** [comment]
It has already has a a close button on the left and you can middle click on it to close it. Right click  moves a window into the master area. Closing a window with a context menu kind of seems like some extra steps that are not really needed. But I'd like to hear your thoughts on it, my perspective is pretty far from that of a first time user...

**Comment by marek-lach** [comment]
> It has already has a a close button on the left and you can middle click on it to close it. Right click moves a window into the master area. Closing a window with a context menu kind of seems like some extra steps that are not really needed. But I'd like to hear your thoughts on it, my perspective is pretty far from that of a first time user...

Ah... cool!
