### ISSUE TITLE
Things to report

### ISSUE THREAD

**Issue by federicotorrielli** [instantOS/instantOS#111]
Hi, let me start by telling you how happy I am with this distribution: it's exactly what I wanted and, of course, I would like to contribute to the project in any way that I can.
But... there are some problems that I encountered that I know that can be fixed in a matter of days.

1) **Better power settings**: by default, InstantOS does not permit hybernation without a swap partition. For laptops, this is a huge one. Swap partitions are used less and less every day and instead I would like to propose to create a swap file or swap in-ram only by default, if there's no swap partition set up.

2) **Brightness settings are not good**: InstantOS should care about F86X brightness changes on the keyboard. Right now it enables and disables the screen only, without modifying the brightness on the screen. ([Video of the brightness bug](https://streamable.com/j13dot))

3) **GTK-3.0 theme is reset every boot-up**. Every time I boot-up, my GTK-3.0 settings are reset on the defaults of InstantOS. I tried to put the 0 inside of the dotfiles config but nothing changed. So everytime I have to go inside of lxappearance and hit "Apply" to re-apply my custom changes.

Apart from these problems I'm having a blast with the distro! Thanks!

Final Note: I would like to see better support for **IPFS** inside the system, it's a great idea.

**Comment by con-f-use** [comment]
1. instantOS uses systemd-swap to allocate swap files dynamically as they are needed. That is more RAM efficient than a fixed-size swap file but also means that hybernation doesn't work out of the box. You can either use suspend instead or choose to manually partition and create a swap partition that is slightly larger than your RAM.
2. It generally cares about the F86X birghtness keys on keyboards. Works on my two laptops. If it doesn't for you, then that is a bug or incompatibility and you should open a separate issue and be sure to include debug and hardware information.
3. No idea what's happening there. @paperbenni do you?

I agree, IPFS is a great idea. It is also a very niche thing that most users do not care about. So it is better left optional and for the user to configure. InstantOS is as welcoming for that as every other Archlinux-based distribution. If you have good, concrete ideas as to what exactly you want done with IPFS and how instantOS should leverage IPFS, we'd be happy to discuss them on the [discord channel](https://discord.io/instantos). The issues section here on github is more of a place for development and less for vague "I'd like to do something with random cool technology".

**Comment by paperbenni** [comment]
For setting a custom gtk theme you need to disable autotheming in settings->appearance->autotheming
Btw I saw on discord you wanted to elaborate on your plans with ipfs, I would also like to get a copy of the document you plan on writing :)

**Comment by federicotorrielli** [comment]
Thanks for the tip for GTK! Understood.
Yes, I'm now in the process of gathering all my ideas before writing a document. I'll put it on discord as soon as I can. I don't have much free time thanks to research and Uni, but I'll do my best.
