### ISSUE TITLE
autostart.sh not running on login.

### ISSUE THREAD

**Issue by quasigod-io** [instantOS/instantOS#117]
When I log in the autostart.sh does not appear to be running. I am attempting to use it to set my refresh rate. I tried making it executable but it did not fix it.

**Comment by paperbenni** [comment]
My first guess would be that it does run but it accidentally runs before the stock settings get applied, meaning your settings get overwritten.
You can check if it runs by adding
```sh
echo 'running' > ~/autostartworks
```
to your autostart script, rebooting and checking if the file ~/autostartworks exists

Also just to be sure, your autostart file is located at ~/.config/instantos/autostart.sh right?

**Comment by quasigod-io** [comment]
Ah looks like you're right, thanks.

Do you know of any fix to my display settings not saving with nvidia-settings? I have the line "VertRefresh     48.0 - 240.0" in my xorg.conf but it seems to be getting overwritten by another service.

**Comment by quasigod-io** [comment]
Nevermind, it was simply the autorandr config overwriting the xorg.conf, thanks for the help!
