### ISSUE TITLE
Can you add the Chinese (Traditional) language to instantOS ?

### ISSUE THREAD

**Issue by litszwaiboris** [instantOS/instantOS#118]

**Comment by con-f-use** [comment]
> Internationalization is one of those things that eats a lot of time and the majority of the world’s computer users, knows standard English, so there’s not much reward for the work put into internationalization. We’re sorry, but we have to prioritize other things for now.

From the [FAQ](https://instantos.io/faq#my-keyboard-layout-doesnt-work-with-instantos-and-language-support-sucks)
