### ISSUE TITLE
Shutdown / reboot commands run from the gui at the top hang.

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantOS#12]
Hello i'm fully able to shutdown/ reboot from the cli but when i use the gui it hangs with only a blinking _ at the top left corner.
:edit
and a black background.

**Comment by paperbenni** [comment]
What command are you using to shut down from cli?
can you run
```instantshutdown | tee ~/shutdownlog```
in a terminal and send me the then created file ~/shutdownlog ?

**Comment by NicTanghe** [comment]
sudo shutdown 0 for shutdown 
and
sudo shutdown -r 0 for reboot

ill send in the shutdownlog after i figure out hoz to run a script at startup.
cronie doesn't seem to work and i can't find anny logs :(

**Comment by paperbenni** [comment]
Any command in ~/.instantautostart will be run at startup. 
But you don't need that for the shutdown thing.

**Comment by NicTanghe** [comment]
hmm i don't think the file was even generated.
but i dit give my pc more time this time and it did eventually shut down just slower.
i'l close now.

**Comment by paperbenni** [comment]
That's strange, because the GUI actually runs shutdown now in the background.
