### ISSUE TITLE
Install hangs at "downloading installer dependencies"

### ISSUE THREAD

**Issue by longtomsa** [instantOS/instantOS#128]
Live version works.  When trying to install and I press the install button a message at the bottom appears saying "downloading installer dependencies".  This is were it stays.  I assume that it tries to reach a server which isn't reachable.

**To Reproduce**
Download latest iso.
Install from life instance.

**Expected behavior**
OS gets installed.

**Additional context**
I have checked my internet connection and can access the public internet without issues.

To add:

Using the curl installer I get the following error:

os-proper-1.79-1-x86.pkg.tar.zst is corrupted
downloading packages failed.

Hope this helps to narrow it down.

Another update

Re-downloaded and re-wrote to usb using different tool - same result.

Thank you.

**Comment by con-f-use** [comment]
Can you try again with a stable internet connection.

**Comment by longtomsa** [comment]
> Can you try again with a stable internet connection.

Yes - have done.  Internet connection is good and stable.  20 up 50 down. It is syncing package databases and downloads os-proper.  Then "checking package integrity" error os-proper signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust.  
Hope this helps.

**Comment by paperbenni** [comment]
Thank you for brining this up, the issue was indeed a changed arch keyring. I have created a fix for the issue
https://github.com/instantOS/instantARCH/commit/15e5c200aa52d5290d16125ab8cd170556d17ca9
Installation from the beta 6 iso should be working again

**Comment by longtomsa** [comment]
Installation went as designed.  Thank you all.  Case closed.
