### ISSUE TITLE
Change screen rotation [Question]

### ISSUE THREAD

**Issue by marek-lach** [instantOS/instantOS#13]
This is more a question I have.

I have taken a look into the Settings application, and found display scaling, which is nice for Hdpi displays, but I would also need to rotate my screen, because my computer defaults into portrait mode, so I then need to change the screen orientation into landscape at the user-level.

I am just not really sure how to do this. Is there a particular config I should edit through the terminal?

Thanks,

**Comment by paperbenni** [comment]
I don't recall adding in Hdpi scaling, must be a third party application that is preinstalled. Where did you find hidpi?
To change the rotation, go into settings->display->change display settings, right click on the display you want to rotate and you should have a submenu for choosing rotation. If you're done, click apply. To make changes persistent over reboots, go into settings->display->make current display settings permanent.

**Comment by marek-lach** [comment]
> To change the rotation, go into settings->display->change display settings, right click on the display you want to rotate and you should have a submenu for choosing rotation. If you're done, click apply. To make changes persistent over reboots, go into settings->display->make current display settings permanent.

Aha! Found it. Much thanks!

> I don't recall adding in Hdpi scaling, must be a third party application that is preinstalled. Where did you find that?

You are right, it may not be Hdpi support proper yet, but at least the screen resolution is detected correctly out of the box, which nevertheless does make the windows and fonts look a bit better than I usually encounter.
