### ISSUE TITLE
Recent update broke chromium (libFLAC.so.8)

### ISSUE THREAD

**Issue by luphoria** [instantOS/instantOS#134]
**Describe the bug**
Presumably after a major instantOS update, chromium stopped working. It spit the error:
```
/usr/lib/chromium/chromium: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
```
My hotfix to the issue was a symlink: `sudo ln -s /usr/lib/libFLAC.so /usr/lib/libFLAC.so.8`

**To Reproduce**
Not totally clear. However, from my best understanding, it has to do with a recent system update to `instantwm-instantOS beta6-96-g3ba7b`

**Expected behavior**
libFLAC.so.8 should not disappear

**Device (only relevant in some cases):**
- instantwm-instantOS beta6-96-g3ba7b

**Comment by paperbenni** [comment]
This likely doesn't have anything to do with instantos
The error you're getting is a library error. Basically chromium needs the file libFLAC.so.8 which belongs to another package. If the package is on an older version, then the file might be called libFLAC.so.7, chromium looks for 8 which doesn't exist yet and throws an error. Similarly if the package version is newer than chromium expects, e.g. chromium wants 7, then it also throws an error. Neither libFLAC or the chromium package are maintained by me, and my best guess is that some script to get a proprietary program working replaced the library

**Comment by luphoria** [comment]
Gotcha
