### ISSUE TITLE
Updates/Install very slow

### ISSUE THREAD

**Issue by rawsta** [instantOS/instantOS#135]
**Describe the bug**
Updating is really slow

**To Reproduce**
1. In terminal, enter: 'yay -S neomutt'
2. Wait for eternity

**Expected behavior**
Install the desired program.

**Additional context**
When I try to install a new program (Neomutt in this case) it takes an eternity to get anything. (aborted after 10+ minutes)
Even while updating, it takes a long, long time to download the sources. (~5min.)

Maybe something on my side. It's a quite fresh installation with minor changes.  

It's a ThinkPad t470 with instantOS with only a few additional tools installed.

Did I do something wrong?

**Comment by paperbenni** [comment]
can you give me a log or screenshot of what the output is when trying to install something?
