### ISSUE TITLE
Installer: `iroot: command not found`

### ISSUE THREAD

**Issue by luphoria** [instantOS/instantOS#136]
**Describe the bug**
instantOS beta 7 installer does not work, because `iroot: command not found`.
**To Reproduce**
1. Download instantos v7 beta from https://github.com/instantOS/instantOS/releases/download/v7-beta/instantos_beta7.iso
2. Attempt to install with the gui
4. Switch to desktop 2 to see logs

**Expected behavior**
Install.

**Device (only relevant in some cases):**
Prebuilt - steam deck. 

**Additional context**
Don't know what `iroot` is, and it wasn't on AUR or pacman mirrors.

**Comment by paperbenni** [comment]
Hm, knowing a few things would probably make this easier to fix
at which point does the installer fail? Does it fail after going through the questions or does it fail before install has started?
Is there anything interesting in the output? Does it offer to upload the logs to ix.io?

**Comment by luphoria** [comment]
> Hm, knowing a few things would probably make this easier to fix at which point does the installer fail? Does it fail after going through the questions or does it fail before install has started? Is there anything interesting in the output? Does it offer to upload the logs to ix.io?

Everything gets created, and it finishes with the confirm prompt going over all the install settings (but, none of the install settings are there!). You can see in logs that it failed `iroot` calls a few times already which probably has to do that. It fails after you finally start install. 
Probably just missing iroot binary in b7. But i couldn't find where to actually polyfill iroot, so couldn't monkeypatch it.

**Comment by paperbenni** [comment]
I did some changes on the installer, is the issue still present?

**Comment by luphoria** [comment]
> I did some changes on the installer, is the issue still present?

Yes. I'm going to try with just beta6 and then upgrade instead. But ofc issue is still present.

**Comment by luphoria** [comment]
Beta 6 is broken, but I tried beta 7 one more time and it worked :D

**Comment by Plokil** [comment]
Connecting an Ethernet cable made the installer work for me

**Comment by gasdiver** [comment]
I found this thread after having the same iroot issue as described above. Beta7. Just sharing the information, thanks for all your hard work.

**Comment by luphoria** [comment]
There probably is some error in retrieving the package? I don't know how the installer works. Should I reopen this issue?
