### ISSUE TITLE
[question] how to add scripts to the win+y menu

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantOS#14]
maybe a nuub question but how do i add scripts to the y menu and give them a icon?

also some programs like vscode and houdini diden't show up automatically.

**Comment by paperbenni** [comment]
Ok, I haven't extensively tested this, but run the command 
```yay -S alacarte; { grep -q 'gnome-' /etc/environment || echo 'XDG_MENU_PREFIX=gnome-' | sudo tee -a /etc/environment } ```
in a terminal and reboot. 
After that you should have an application called Alacarte where you can set up menu entries with custom names, icons and commands.

**Comment by NicTanghe** [comment]
i'l confirm later went on a role lookibng for a replacement for instant because i zs having issues with installing renderman.
evrthithing else i tried ws shit and coulnd't even get it zorking in centos so i'm back here noz prolly 4 good.

**Comment by NicTanghe** [comment]
i get a lot of predictable errors.
grep: gnome-: no such file or directory
/etc/environment:QT_QPA_PLATFORMTHEME=qt5ct
XDG_MENU_PREFIX=gnome-

**Comment by paperbenni** [comment]
where do you get these? When opening the menu?

**Comment by paperbenni** [comment]
> grep: gnome-: no such file or directory
This just looks like you misspelled the command. did you type in the /etc/environment?

**Comment by paperbenni** [comment]
You should NOT misspell this command, it can break your system.

**Comment by paperbenni** [comment]
> /etc/environment:QT_QPA_PLATFORMTHEME=qt5ct
XDG_MENU_PREFIX=gnome-

This is not an error, you can ignore it.

**Comment by NicTanghe** [comment]
ok so it worked.
few more questions tho.
1. should i just come to the discord server
2. sudo doesnt seem to work in there annyway u know of around that? like zith a gui prompt for password in a bin file that then runs the script or ?

**Comment by paperbenni** [comment]
For support probably yes, the link is on the website. 
For feature requests and bug reports, do github issues.

**Comment by paperbenni** [comment]
![grafik](https://user-images.githubusercontent.com/15818888/82358400-c3949f80-9a06-11ea-982b-efaf54107ee2.png)
Is that you?

**Comment by NicTanghe** [comment]
y no mic tho

**Comment by NicTanghe** [comment]
seems selecting that launch in terminal fixes the issue.
