### ISSUE TITLE
EIther installing awesome-terminal-fonts-git or p10k makes it impossable to open a terminal.

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantOS#15]
Hello so after i intalled awesome-terminal-fonts-git nez terminqls i open close in frame or 3.

**Comment by paperbenni** [comment]
Can you still open xterm? What does launching urxvt from xterm say? Try opening the Super + Space menu, type dash and press Shift + Return to open. Does that still work?

**Comment by NicTanghe** [comment]
i also couldn4t install xterm but after reinstalling instant i noticed that they actually probably has something to do with the combination of 
st / p10k and Houdini. https://www.sidefx.com/download/

Issues began this install when i installed Houdini. so its probably non related to awesome-terminal-fonts-git.

might also have something to do with sudo nice -n -12 program but i don't think so.
of to another reinstall sigh.

**Comment by NicTanghe** [comment]
i'm on the default st build now but i'm to scared to try to reinstall the p10k zsh theme for now.
if maybe the prompt for nvidea drivers i fixet i'll try again with the p10k theme.

**Comment by con-f-use** [comment]
Closed for inactivity.
