### ISSUE TITLE
Don't see the InstantOS boot option when starting

### ISSUE THREAD

**Issue by GSablayrolles** [instantOS/instantOS#153]
**Describe the bug**
I have installed InstantOS via USB and I successfully installed it. However after rebooting it at the end, my computer does not propose to boot on the InstantOS (when I restart it I don't see the boot option when entering the bios either).

**Expected behavior**
See my Windows and InstantOS boot option 

**Device (only relevant in some cases):**
Asus Zenbook

**Additional context**
I disabled the fast boot and secure boot to be able to install it but even after installing it I can't acces InstantOS. In the docs it said when booting in the live version choose  "boot existing OS" but I don't have this option.

**Comment by instantuzer** [comment]
- you are dual booting?
- what happens at startup, does it still boot windows?
- did you manually partition instantos?
- if so, do u have the output of > lsblk

**Comment by GSablayrolles** [comment]
Yes I am dual booting and my laptop still boot on windows. 
I had to manually allocate space on my disk with windows because Bitlocker was on.

I think there is an issue with Grub so I am trying something, I will send you the output of lsblk if it doesn't work

**Comment by GSablayrolles** [comment]
UPDATE : So I tried to reinstall the Beta7 and it shows that > iroot  : command not found
So I will try with this Issue and see if the istallation proceed : https://github.com/instantOS/instantOS/issues/136

**Comment by GSablayrolles** [comment]
FINAL : When I installed I just choose the wrong EFI disk and was not able to boot. 
But somehow, I discover the iroot issue and cannot install InstantOS beta7 on my laptop

**Comment by GSablayrolles** [comment]
FINAL : When I installed I just choose the wrong EFI disk and was not able to boot.
But somehow, I discover the iroot issue and cannot install InstantOS beta7 on my laptop
