### ISSUE TITLE
powerline font not working

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantOS#16]
Power line isn't working I assume it should work on a clean installation.
Also installing awsome-terminal-git doesn't fix anything and just breaks evrything.
![capt](https://user-images.githubusercontent.com/13624265/82312245-151d3a00-99c7-11ea-87df-6bb57cb17f1d.png)

**Comment by NicTanghe** [comment]
note: it does work in luke's build of ST 
![capt](https://user-images.githubusercontent.com/13624265/82312956-05522580-99c8-11ea-9289-1d0ce2352eea.png)
https://github.com/LukeSmithxyz/st

**Comment by NicTanghe** [comment]
ok after furether research it seems consoles launched from middle mouse on desktop or shift enter and consoles launched from other consoles function diferently.

**Comment by paperbenni** [comment]
instantOS now uses luke-st by default, you can try if that solves the issue.

**Comment by NicTanghe** [comment]
ok 1. thats pretty fucking awsome.
i must say that it powerline was only fixed for me in the power + enter mode when i installed inetutils and used hostname to change my hostname propperly. I ws also running into issues with other programs becouse of it (houdini) i advice you do do this by default.

**Comment by NicTanghe** [comment]
Oh and there's stil a weird ofset now
![image](https://user-images.githubusercontent.com/13624265/82335314-70602400-99e9-11ea-9cd5-9c7cc9884af3.png)

**Comment by paperbenni** [comment]
Super + print screenshots to the pictures folder not to the clipboard.

**Comment by paperbenni** [comment]
st has no problems rendering any symbols, closing this
