### ISSUE TITLE
VirtualBox Support

### ISSUE THREAD

**Issue by Justinzobel** [instantOS/instantOS#17]
Booted the ISO in VirtualBox with EFI on, it does the initial boot but doesn't get to GUI.

**Comment by paperbenni** [comment]
That's odd, I'm using virtualbox to test my ISO's. Do you use any special settings? Do other Distros work with EFI on? Are there any error messages? What does the screen look like when it gets stuck?
Are you able to go to tty?

**Comment by Justinzobel** [comment]
Screen is below. I can get to TTY3. 
![VirtualBox_instantOS_24_05_2020_20_02_36](https://user-images.githubusercontent.com/1370117/82751898-932f7580-9df9-11ea-9e3a-a2fa9dff5473.png)

I can boot my Win10 VM that is EFI enabled.

**Comment by paperbenni** [comment]
Have you tried resetting the vm? (Right Ctrl Key + R)?
It sometimes locks up lightdm in VMs, never does that on real hardware...

**Comment by Justinzobel** [comment]
Several times. What's the live username and password so I can check lightdm logs, etc.

**Comment by paperbenni** [comment]
username: instantos
password: instantos
sudo has no password

**Comment by Justinzobel** [comment]
![image](https://user-images.githubusercontent.com/1370117/82770570-27d8b880-9e78-11ea-946c-594c41e8193f.png)

**Comment by Justinzobel** [comment]
Closing, lost interest.

**Comment by paperbenni** [comment]
Sorry, Kinda forgot about this issue. Another person also had this issue, it was solved by installing accountsservice although I think it requires a reboot. 
It will be preinstalled on the next iso.

**Comment by paperbenni** [comment]
There also is a cli installer, instructions are on the downloads page.
