### ISSUE TITLE
"NetworkManager is not running..."

### ISSUE THREAD

**Issue by alduraibi** [instantOS/instantOS#18]
I'm trying to install instantOS but I'm not able to because I can't connect to the internet. When I click on the network applet in the top right corner it says "NetworkManager is not running...". 

If it helps, I tested Manjaro from the same bootable usb and was able to connect to the internet.

10th Gen Intel® Core™ i7-1065G7 with Intel® 802.11AX (2 x 2) & Bluetooth® 5.0

**Comment by paperbenni** [comment]
you need to run
sudo systemctl start NetworkManager
It will be fixed in the next iso build

**Comment by alduraibi** [comment]
It worked, thanks!
