### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Z3r0ish** [instantOS/instantOS#2]
I keep getting an error even though I can access the internet (I'm using an Ethernet cable)
The error:
"An internet connection is required to install instantOS"
Any idea how to fix this issue?

**Comment by paperbenni** [comment]
Are you able to access the web via Firefox in the live session? The internet checker just pings google...
What does the network applet in the top left right say?

**Comment by paperbenni** [comment]
The new build has completely reworked the installer, can you let me know if it worked for you?
https://github.com/instantOS/instantOS/releases/download/beta2/instantos_beta_2.iso
