### ISSUE TITLE
Allow users to customize

### ISSUE THREAD

**Issue by adeleglise** [instantOS/instantOS#21]
I would be great if can document how people can :

- Change fonts : I've changed the fonts for my terminal in my .Xressources and xrdb it, but it get overwritten at reboot

**Comment by paperbenni** [comment]
It is documented. https://instantos.github.io/instantos.github.io/youtube/customize

**Comment by adeleglise** [comment]
So, why the .Xresources get overwritten at reboot ?

**Comment by paperbenni** [comment]
It says on the website. You need to disable theming to manually change things. 
But I'll maybe add a pop-up that detects manual changes and offers to disable management for that file.

**Comment by adeleglise** [comment]
OK, thanks for your patience.
