### ISSUE TITLE
Can I install this OS overtop of my arch linux install?

### ISSUE THREAD

**Issue by Titaniumtown** [instantOS/instantOS#24]
Super interested in this project, but i was wondering, could I install this on top of my arch linux install? i already have everything as i like it. Since it's arch based, i was thinking that i could just install the packages in my current install. 

Thoughts?

**Comment by xavier124** [comment]
I would recommend just running instantOS in VirtualBox/unused machine, seeing if you like it, and then installing it on your main

**Comment by Titaniumtown** [comment]
What about installing the window manager and stuff manually? Would that work?

**Comment by paperbenni** [comment]
Yes. You can add http://instantos.surge.sh/ to your mirrorlist and just install them via pacman. Or you could manually install binary packages from the website index

**Comment by Titaniumtown** [comment]
Ok thanks! I'm actually working on a fetch script for bedrock linux to install instantOS as a stratum: https://github.com/bedrocklinux/bedrocklinux-userland/pull/186#issue-438748531

**Comment by paperbenni** [comment]
Cool. I'm not too familiar with bedrock, but I can help with any instantOS questions when implementing this.

**Comment by Titaniumtown** [comment]
1 question, i see that the instantos package needs grub-instantos, could you make that package bootloader-agnostic or something? Then tell the installer to install grub-instantos? Because I'm just installing the dependencies of instantos (excluding grub-instantos) and I feel like that's a janky solution. Like if you add more packages and the such.

**Comment by paperbenni** [comment]
grub-instantos is just the theme, you can install it anywhere without any risk of breaking anything.

**Comment by Titaniumtown** [comment]
Also, this is manjaro based, isn't it? Not arch linux based? Because currently I have it setup with arch linux's repos. Should I change that?

**Comment by Titaniumtown** [comment]
> grub-instantos is just the theme, you can install it anywhere without any risk of breaking anything.

Some people don't use grub though, especially when you're using zfs with bedrock linux (like I am) there is a major issue with that not booting.

**Comment by Titaniumtown** [comment]
So, does it not install grub? Is that what you're saying?

**Comment by paperbenni** [comment]
Yes. But even if you have the grub package installed, it doesn't actually do anything before you run install-grub /dev/sdx

**Comment by Titaniumtown** [comment]
Ok, got it.

**Comment by Titaniumtown** [comment]
Also, this is manjaro based, isn't it? Not arch linux based? Because currently I have it setup with arch linux's repos. Should I change that?

**Comment by paperbenni** [comment]
No, it's arch based. It used to be manjaro based. Is there still a place left that says it's manjaro based?

**Comment by Titaniumtown** [comment]
No, I just heard it was from a while back. thanks for the clarification!

**Comment by Titaniumtown** [comment]
Looks like bedrock linux support isn't going to be implementeed, as instantOS can just be installed inside of arch linux.

**Comment by Titaniumtown** [comment]
But i've done some testing installing the instantos package, on my arch linux install. and TONS of stuff doesnt work, like SUPER+SPACE doesnt do anything. the buttons in the settings dont work. any thoughts?

**Comment by Titaniumtown** [comment]
Update, got it working. had to `yay -S instantassist instantconf instantcursors instantdepend instantdotfiles instantfonts instantlock instantmenu instantsettings instantthemes rofi-git instantos` to get everything working
