### ISSUE TITLE
Unable to boot in Virtualbox with 3D acceleration enabled

### ISSUE THREAD

**Issue by Gamegenorator** [instantOS/instantOS#26]
Upon trying to install Instant OS in Virtualbox, the installer runs for a while, and then autoreboots as I'd expect it to, however when trying to boot Instant OS without the installation iso it gets to this point in the boot process:

![unknown (1)](https://user-images.githubusercontent.com/38223298/85599515-6e4d3e80-b601-11ea-820f-836d17f32f08.png)

And then the screen goes black and the OS never boots up.

I'm not a highly advanced Linux user but I will do my best to answer questions about this issue if I can.

**Comment by Gamegenorator** [comment]
Issue was caused by having 3D acceleration enabled in VirtualBox, disabling 3D acceleration fixes the issue.

![image](https://user-images.githubusercontent.com/38223298/85446970-f2dc8600-b549-11ea-95c0-804064102719.png)

**Comment by paperbenni** [comment]
3d accelleration should work. I had to installl ```xf86-video-vmware``` to get it working. Is that also the case for you?

**Comment by Gamegenorator** [comment]
@paperbenni Installing `xf86-video-vmware` does not fix the issue for me, it still gets stuck on boot.

**Comment by mj1911** [comment]
Hmm, I have 3D accel enabled in Beta5 with no issues yet.  VBox 6.1.14, Win10 host, Intel i5 3470 with integrated HD gfx.

**Comment by Gamegenorator** [comment]
@mj1911 Sorry for the late reply, it appears to have solved itself somewhere between the 3rd beta and the 5th. I will now close this issue.
