### ISSUE TITLE
Cannot run into live session (beta v3)

### ISSUE THREAD

**Issue by forkthat** [instantOS/instantOS#27]
Text on the screen goes like this:

>...
>:: running hook [archiso_pxe_nfs]
>:: Mounting '/dev/disk/by-label/ARCH_202006' to '/run/archiso/bootmnt'
>Waiting 30 seconds for device /dev/disk/by-label/ARCH_202006 ...
>ERROR: '/dev/disk/by-label/ARCH_202006' device did not show up after 30 seconds...
>        Falling back to interactive prompt
>        You can try to fix the problem manually, log out when you are finished
>sh: can't access tty: job control turned off
>[rootfs ]#

**Comment by paperbenni** [comment]
Can you boot a normal arch iso?

**Comment by forkthat** [comment]
Yes, I can.  Sorry, I forgot to include my hardware specs:  Ryzen 5 2500U, Radeon 535.  My laptop is Acer Aspire 3 A315-41G-R4BW.

**Comment by paperbenni** [comment]
The CLI installer probably should work. You can run it off a normal arch iso

**Comment by forkthat** [comment]
Okay, I will try.

**Comment by liorlobel** [comment]
Hi, Thanks for making this very elegant desktop. 
I'm having the same problem on Thinkpad Extreme. I used dd to burn the iso image. 
Can boot arch iso. But this seems an annoyance.

**Comment by paperbenni** [comment]
Are you on the beta 4 iso?

**Comment by liorlobel** [comment]
Yes

**Comment by paperbenni** [comment]
Ok, I have a few questions: 
did you get the same error as forkthat?
What are your specs? Especially what gpu do you have?
What is your storage setup? Any external drives? Multiple internal ones? Anything special like raid?

**Comment by liorlobel** [comment]
Yes. An error about mounting a partion.
My laptop is the Lenovo X1 Exterme Gen2.  intel i9.  GTX 1650.
I have 2 nvme drives, not raid.
No external.

**Comment by paperbenni** [comment]
Are you also able to boot a normal arch iso?

**Comment by liorlobel** [comment]
Yes. I've installed Arch before on this laptop the arch way :)

**Comment by paperbenni** [comment]
Ok, and what is the error you're getting? Is it the same as @forkthat had?
And what program did you use to burn the iso?

**Comment by liorlobel** [comment]
I used a frontend for dd.
I get an error when
Mounting '/dev/disk/by-label/ARCH_202007'

It fails and gives up after 30 sec

**Comment by paperbenni** [comment]
Hm, would you mind trying with etcher?

**Comment by liorlobel** [comment]
Sure, trying now

**Comment by liorlobel** [comment]
Its works fine with Etcher
