### ISSUE TITLE
"[FAILED] Failed to start Light Display Manager"

### ISSUE THREAD

**Issue by freder** [instantOS/instantOS#3]
I just tried to boot the .iso from a usb drive, but it hangs...

![instantos](https://user-images.githubusercontent.com/724844/81409269-1c2e8780-913f-11ea-9c16-20c08cf58a20.jpg)

**Comment by paperbenni** [comment]
That's interesting. What specs does your pc have? 
Do you happen to have a vega gpu/apu?

**Comment by freder** [comment]
I already have a manjaro installation on the system, which runs fine.
it's an nvidia rtx gpu, and the error occurs with both free and non-free graphics drivers selected.

**Comment by NicTanghe** [comment]
I have the same issue but only when selecting proprietary drivers at startup.
my gpu is a 750ti 2gb and my cpu is a 3950x.

**Comment by paperbenni** [comment]
Beta build 2 is now out, in my testing it fixed the issue that some graphics cards had. 
https://github.com/instantOS/instantOS/releases/download/beta2/instantos_beta_2.iso

**Comment by con-f-use** [comment]
Closed for inactivity and possible fix.
