### ISSUE TITLE
GPU HDMI not recognized in xrandr

### ISSUE THREAD

**Issue by omrygin** [instantOS/instantOS#30]
Hi,
My HDMI plug is not recognized in `xrandr`. I have a GeForce GTX 1660. `nvidia-smi` does recognize the GPU.
Probably the WM runs on the integrated graphics?
How can I turn it to run on the GPU?

Thanks

**Comment by paperbenni** [comment]
Is the problem on the live session or the installed version?
And do you have integrated graphics like intel or vega?

**Comment by omrygin** [comment]
The issue is in the installed version.
I do have integrated graphics from my Intel CPU

**Comment by paperbenni** [comment]
Does installing nvidia-dkms solve the issue?

**Comment by omrygin** [comment]
It does not.
I tried to follow https://wiki.archlinux.org/index.php/Nvidia-xrun#Automatically_run_window_manager
by creating `.nvidia-xinitrc` in home folder, and writing
```
if [ $# -gt 0 ]; then
  $*
else
  instantwm
fi
```
however nothing happened. If I recall correctly this is what I did in previous OS, but I may be wrong.
In anycase, the HDMI is still not recognized by `xrandr`.

**Comment by paperbenni** [comment]
Try this:
going to tty, logging in as your user, run ```instantdotfiles```
And then execute ```startx```
Does that work?
instantOS uses lightdm as a display manager, I suspect it fails for some reason.

**Comment by omrygin** [comment]
I do realize now that lightdm does not even launch after boot, it goes straight to instantWM, logged as my user. 
How is that possible? Is it a settings issue or something else?

In any case, when I do what you asked, the instantWM session that starts has no background and no battery/audio info in the top right.
Also the terminal colors are different.
Still `xrandr` does not recognize HDMI

**Comment by paperbenni** [comment]
How are you getting output without HDMI? Display port?

**Comment by omrygin** [comment]
Sorry, I use a laptop. So it does recognize my laptop's screen, which is embedded DP if that counts.
My HDMI is connected only to the GPU

**Comment by paperbenni** [comment]
Oh, is it an optimus laptop?

**Comment by omrygin** [comment]
It is. Previous distro installs I made (base arch, manjaro) somehow made it work, using some of the steps I mentioned earlier.
My goal is to make X run only on the GPU, I don't care about power usage.

**Comment by paperbenni** [comment]
Lightdm is running, it just has autologin by default. 
You're likely using hybrid graphics at the moment which is why the monitor doesn't get detected. 
The thing you did get working on the second monitor was a second x session. You also only started the WM, the primary x session also has additional stuff running for wallpaper, status and theming that was missing from the second one.

**Comment by paperbenni** [comment]
I unfortunately don't have any device to test this on, but you could try using ```optimus-manager``` (available in the AUR)
Alternatively you could go the manual route by following this (you'd have to follow the lightdm instructions)
![grafik](https://user-images.githubusercontent.com/15818888/85847648-156bda80-b7a8-11ea-9694-6f8649b6d44b.png)

**Comment by omrygin** [comment]
Great, that did it. Thank you.

**Comment by paperbenni** [comment]
Which of these did it? optimus-manager or the manual way?

**Comment by omrygin** [comment]
Manual, I did not try optimus.
