### ISSUE TITLE
Sound level goes back to %100 after setting it higher than %100

### ISSUE THREAD

**Issue by pinetaco** [instantOS/instantOS#31]
whenever i set the sound level of firefox to more than %100 and close the settings it goes back to 100.

**Comment by paperbenni** [comment]
By settings you mean the ones that  super + shift clicking on the status bar brings up?
Firefox has a separate slider for each tab, so closing a tab undoes any settings done to it. Are you able to set the overall volume to higher than 100%?
By the way setting the volume of anything to higher than 100% is not recommended, you should turn your speakers and volume inside for instance the youtube player to 100% before resorting to >100% anywhere.
