### ISSUE TITLE
Delete doesn't work in the shell in `st`

### ISSUE THREAD

**Issue by omrygin** [instantOS/instantOS#33]
Hi,
The delete key seems to not work for me in `st`.
It works in `vim` when ran in `st`, as well as works in `xterm` and `urxvt` that came pre-installed.
So just in the shell (which I use `bash`) it seems to make issues, and just in `st`

**Comment by NicTanghe** [comment]
I don't know if I misunderstood you but The default terminal is st

**Comment by paperbenni** [comment]
What keyboard layout are you using? And are you using the instantOS zsh configuration?

**Comment by omrygin** [comment]
I am using en-us layout. I switched to `bash`. Should that make a difference?

**Comment by omrygin** [comment]
Changing the shell to `zsh` fixed it. Why is that so?

**Comment by paperbenni** [comment]
bash uses the vim hotkeys by default. That could be a cause for it. Maybe I should change that...

**Comment by con-f-use** [comment]
Or a simple `tput smkx` in the `~/.bashrc` might fix it.
