### ISSUE TITLE
Auto-mount devices

### ISSUE THREAD

**Issue by Titaniumtown** [instantOS/instantOS#35]
Could an option be added to auto-mount devices? Right now, i have to go to my file manager (nautilus) and manually click on it to mount.
Note: I am not using "instantos" i simply installed the package "instantos" from the repo.

**Comment by VuiMuich** [comment]
Udiskie would be a nice fit for this, it lives in the taskbar and is very intuitive to use.

**Comment by Titaniumtown** [comment]
looks like @paperbenni added this! So, I'll close this issue now.
