### ISSUE TITLE
Weird scaling issue with the "instantOS" settings

### ISSUE THREAD

**Issue by Titaniumtown** [instantOS/instantOS#36]
![Screenshot from 2020-06-28 11-46-51](https://user-images.githubusercontent.com/11786225/85952137-3ca3e280-b935-11ea-9234-bd0580126647.png)
Note: I am not using "instantos" i simply installed the package "instantos" from the repo.

**Comment by paperbenni** [comment]
you need to install arc theme and papirus icons.

**Comment by Titaniumtown** [comment]
got it, just saw the message in the discord :)
