### ISSUE TITLE
networkmanager?

### ISSUE THREAD

**Issue by gatlinnewhouse** [instantOS/instantOS#37]
are you planning to use it with `iwd`?

**Comment by paperbenni** [comment]
I have never heard of iwd. It's already using networkmanager but not iwd

**Comment by gatlinnewhouse** [comment]
iwd can be used as a backend for networkmanager.

https://wiki.archlinux.org/index.php/Iwd

**Comment by paperbenni** [comment]
at first glance iwd seems like a very specific non-standard choice. Are there any other distros using it by default?
