### ISSUE TITLE
Artix Linux based iso/install on Artix linux

### ISSUE THREAD

**Issue by Titaniumtown** [instantOS/instantOS#38]
Would it be possible to install instantos on Artix Linux? I'm looking into Artix and am wondering if that would be possible. Another thing, could you possibly provide Artix Linux Based isos?

**Comment by paperbenni** [comment]
Yes, there is experimental Artix support
There isn't an artix base iso yet, but looking at the artix documentation it shouldn't be too hard to do.

**Comment by Titaniumtown** [comment]
Ok, thanks. I've been looking into Artix linux and I was making sure it was possible :)
