### ISSUE TITLE
Compress iso for faster download

### ISSUE THREAD

**Issue by quarkQuark** [instantOS/instantOS#4]
The iso file is large and takes a long time to download - there are some other distros which instead download a zip file you have to extract.
If possible, I think compressing the iso file for download would make this much quicker.

**Comment by marek-lach** [comment]
Or have an alternative mirror directly hosted on Github (like EndeavourOS does it), as that is much faster than SourceForge.

**Comment by paperbenni** [comment]
for now there is an osdn link. It is much faster than sourceforge, But I will also upload a github release.
https://osdn.net/dl/instantos/instantos_1.0.iso

**Comment by paperbenni** [comment]
The new build is released on GitHub and future builds will be put up here too. The iso is also a lot smaller than the previous one. 
https://github.com/instantOS/instantOS/releases/download/beta2/instantos_beta_2.iso

**Comment by paperbenni** [comment]
The ISO is also already compressed, putting 7z on top of that makes a difference of only ~20mb, I wouldn't say that's worth it.
