### ISSUE TITLE
dvtm instead of tmux

### ISSUE THREAD

**Issue by wurosh** [instantOS/instantOS#42]
Switching from a dwm-style workflow in GUIs to an i3/tmux style workflow in the terminal is rather jarring. Have you considered dvtm as an alternative to tmux? It works the same as dwm, but in the terminal. Plus it's suckless software just like st and dwm.

**Comment by paperbenni** [comment]
instantOS is not suckless software, see the about page on the website. And I'm not going to swap out tmux simply because it does the job just as well and is widely used.
