### ISSUE TITLE
default application gui

### ISSUE THREAD

**Issue by Titaniumtown** [instantOS/instantOS#43]
Could a gui be created for selected default applications? Like when you do Super+Enter to open a terminal, it opens st (I use alactritty).

Thoughts?

**Comment by paperbenni** [comment]
Yes, I am working on that

**Comment by Titaniumtown** [comment]
Ok, looking forward to it!

**Comment by paperbenni** [comment]
This is now added

**Comment by adrianinsaval** [comment]
@paperbenni 
https://github.com/instantOS/instantSETTINGS/blob/052927dc33512344a4b99f9675a4d2cd8108292e/settings.sh#L638
https://github.com/instantOS/instantSETTINGS/blob/052927dc33512344a4b99f9675a4d2cd8108292e/settings.sh#L966
could these be changed to use the user set editor? I do manage some dotfiles but i use micro not vim so it's a pain in the ass.
