### ISSUE TITLE
[Installer] Add warning for low battery

### ISSUE THREAD

**Issue by shiftgeist** [instantOS/instantOS#44]
First of all, thank you very much for your efforts! I am pleased that this Disto is on the rise.

I suggest to add a warning when instantOS is installed on a laptop and the power is not plugged in. I was thinking of something like "Warning: Your laptop is not plugged in. Would you like to continue?". (like the other questions at the beginning of the installation).

**Comment by paperbenni** [comment]
very good idea. I'll do that

**Comment by paperbenni** [comment]
This is now added
