### ISSUE TITLE
[Keyboard/Settings] Add screen brightness control

### ISSUE THREAD

**Issue by shiftgeist** [instantOS/instantOS#45]
Currently I am stuck with 100% screen brightness, which isn't bad, unless I sit in a darker environment. I suggest to add a brightness gui control and keyboard shortcuts. There is a media key for brightness `+`/`-` but i could only figure out the key codes (from showkey: `+ 225`/`- 224`) and not their names. Not sure if this is universal. One solution I found is to use `xbacklight` to control the screen brightness: https://askubuntu.com/a/823691/774009, also not sure if this works outside of i3.

**Comment by paperbenni** [comment]
There actually is a screen brightness slider, it's accessed in the super +a menu by pressing b
But I'll also add it to the display settings, maybe it's more apparent there. As for media keys, if you can somehow get the xlib key names of the ones you have I can add them no problem. xbacklight seems to be intel only, instantOS has a more general solution accessible from outside, it is accessible using the script in /usr/share/instantassist/utils/b.sh

**Comment by shiftgeist** [comment]
Changing the display brightness with the `brightness slider` in the instantAssistant works for me.

**Comment by con-f-use** [comment]
Brightness keys work for me on my laptop. Support was added here: https://github.com/instantOS/instantWM/blob/master/config.def.h#L357

**Comment by forkthat** [comment]
Hello, one thing I noticed about the birghtness is that for every reboot, the screen brightness resets to 100%.

**Comment by con-f-use** [comment]
Remembering screen brightness setting is now on the todo list.

**Comment by paperbenni** [comment]
It should already be remembering the brightness. That's the weird part
