### ISSUE TITLE
[ Keyboard ] Add Volume Popup when changing volume using the keyboard keys

### ISSUE THREAD

**Issue by RubenHetKonijn** [instantOS/instantOS#49]
I would like a volume popup when chaning volume using the keyboard keys, something ubuntu has, but not as laggy, could also be a llittle bar implemented on the side of the monitor (which i would like better)

**Comment by con-f-use** [comment]
There a plans to add signals to the status bar handler so it can get updated on events like this. That means that the `A <volume>%` in the status bar would update instantaneously when pressing the volume keys. This will, however take some time.
