### ISSUE TITLE
The installer sometimes doesn't run, even if connected to the internet 

### ISSUE THREAD

**Issue by marek-lach** [instantOS/instantOS#5]
See more here: https://forum.archlabslinux.com/t/instantos/4520/15

**Comment by paperbenni** [comment]
Another person also had the same problem, I strangely never ran into it. The next build will be based on arch and also feature a custom installer which will hopefully solve these issues.

**Comment by marek-lach** [comment]
I use Surface Pro 3 and have this issue. Why not just use Calamares (http://calamares.io), that works well enough.

**Comment by paperbenni** [comment]
It actually does currently use Calamares. But it has all sorts of quirks like not running under certain hardware requirements which are actually higher than those of the OS. The new installer can also run as a cli. Here's a demo of an early version. https://asciinema.org/a/329189 
It's not finished yet, I have not tried it on actual hardware, but is coming along nicely

**Comment by marek-lach** [comment]
> It actually does currently use Calamares. But it has all sorts of quirks like not running under certain hardware requirements which are actually higher than those of the OS. The new installer can also run as a cli. Here's a demo of an early version. https://asciinema.org/a/329189
> It's not finished yet, I have not tried it on actual hardware, but is coming along nicely

Oooh, cool!
