### ISSUE TITLE
Touchpad not working on first boot

### ISSUE THREAD

**Issue by forkthat** [instantOS/instantOS#50]
I have freshly installed IOS through the CLI but the touchpad is not working.

**Comment by Titaniumtown** [comment]
Freshly installed "IOS"? Don't you mean OS?

**Comment by forkthat** [comment]
I mean, InstantOS, sorry

**Comment by Titaniumtown** [comment]
oh ok

**Comment by forkthat** [comment]
Solved!:

So after installing `xf86-input-evdev` and `xf86-input-synaptics`, it worked after rebooting the system.  But I don't know how to edit the sensitivity, reversing the direction of scrolling, etc.  I have tried installing xfce4's mouse settings but that didn't work.

**Comment by paperbenni** [comment]
Do the built in mouse settings work

**Comment by forkthat** [comment]
Yes they do, but so does the direction of scrolling of the connected mouse.  Would it be possible that the touchpad and the mouse settings are separated?

**Comment by paperbenni** [comment]
Probably but that's a very specific use case so for now you'll have to do it manually. I did add it to the todo, but it'll probably be a while till that feature gets introduced.
The missing drivers were added to the installer
