### ISSUE TITLE
Using audio slider from InstantAssist does not work

### ISSUE THREAD

**Issue by forkthat** [instantOS/instantOS#51]
The audio does not change when using the shortcuts: Super + A, then pressing A, then modifying the values of the slider, and pressing enter.

Edit:  Also, the keyboard shortcuts for adjusting audio levels do not work.  In my case, Fn + F11 should increase the audio but it does not.

**Comment by forkthat** [comment]
Ok, my bad.  The aiduo changes quite well when watching a Youtube video.  Sorry.

The thing that made me think that the audio was broken was that the audio info on the top right corner was slow to update, like once every 2 seconds.

**Comment by con-f-use** [comment]
See: https://github.com/instantOS/instantOS/issues/49
