### ISSUE TITLE
Cannot accept bluetooth pairing

### ISSUE THREAD

**Issue by forkthat** [instantOS/instantOS#52]
There's a notification that says you should confirm bluetooth pairing but there's no button to be found, in contrast to xfce4's notification having a button to accept pairing.

**Comment by paperbenni** [comment]
instantOS uses dunst for notifications. At the moment you need to right click on it to open the menu containing the buttons. I'll change it to left click, I think that's a lot more intuitive

**Comment by paperbenni** [comment]
![Peek 2020-09-06 13-01](https://user-images.githubusercontent.com/15818888/92324356-3884f700-f041-11ea-9413-aefdeecba579.gif)
I came up with this (excuse the frame rate, but you get the idea), left clicking the notification brings up a menu that allows selecting an option. I already tested this with my phone and was able to pair it via the notification. 
At the moment this is only in master but will arrive in the pacman repos soon

**Comment by forkthat** [comment]
Woah! That's very nice. Hope to see it in a future update!
