### ISSUE TITLE
[Installation] Damaged tar archive

### ISSUE THREAD

**Issue by dt-wark** [instantOS/instantOS#53]
I can't install the system because the installer downloads a corrupted archive.

Maybe you should compare the archive hashes? If they're different, try downloading the archive from another mirror.

![tar](https://user-images.githubusercontent.com/17111538/90014472-2caf4a80-dcb8-11ea-8fe1-238951b48830.jpg)

**Comment by paperbenni** [comment]
Which mirror were you using?

**Comment by dt-wark** [comment]
I didn't choose any mirror.
I just started the installer lol

**Comment by paperbenni** [comment]
ooh, so this is when it's downloading its dependencies
weird that pacman doesn't jump to the next mirror on its own. The corrupted files are from the stock arch repos...
Maybe they had some issues. I'll try clearing and redownloading the db cache if something fails. Does the problem still persist?

**Comment by dt-wark** [comment]
I updated the mirrors list with Reflector:
`reflector --verbose -l 20 -p https --sort rate --save /etc/pacman.d/mirrorlist`

And the installation process started without errors :)
