### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sciroccogti82** [instantOS/instantOS#54]
Bought a new motherboard and cpu a MSI MPG Z490 GAMING PLUS and a i5 10600k, now I can not install instantOS anymore it restarts in the middle of installing. Had no problem at all with the old hardware a i770k and a z270 motherboard, all the other hardware are the same.

**Comment by sciroccogti82** [comment]
Tried to watch what output terminal had before restarting, it was just when installing artix fixes or something like that.

**Comment by paperbenni** [comment]
What happens when you try to boot from the installation?

**Comment by g-shon** [comment]
Have the same issue with BETA 4, the installer crashes and kills the entire Live session. Seems to happen at when the installer gets to mount it says mount failed and kills everything.

**Comment by sciroccogti82** [comment]
Yup beta 4, managed to start it by installing refind so everything but bootloader gets installed.
