### ISSUE TITLE
My laptop won't go to sleep

### ISSUE THREAD

**Issue by larryare** [instantOS/instantOS#56]
My laptop won't go to sleep, display turns off though sound keeps playing.

I'd like to help you to resolve this issue but as I'm not that experienced with Linux, I don't know which file to upload here.

**Comment by con-f-use** [comment]
What does it do, when you run `systemctl suspend` ?

**Comment by larryare** [comment]
Yes, this works. Sorry forgot to mention that it doesn't work when closing the lid. In every other distro I've ran on my laptop (Xiaomi mi notebook pro), everything works fine. Even vanilla arch.

**Comment by con-f-use** [comment]
Did you go through the power management options in the settings menu?

**Comment by larryare** [comment]
Well this was an unexpected one. Why it's set to "Lock Screen" by default?

**Comment by con-f-use** [comment]
Because many people run things like lengthy compilations or encode videos or download large files and want to get their laptop out of the way while these operations continue. It's the less dangerous and therefor more sensible default.
