### ISSUE TITLE
bug | glyph fonts (nerd) not rendering correctly after first install

### ISSUE THREAD

**Issue by RobertLemmens** [instantOS/instantOS#62]
First of all: Awesome OS. Loving it so far, I've actually gone ahead and installed this on my main machine now after using the USB for a while, saying goodbye to a 12 year old Manjaro installation. As for the bug report:

**Description**
After installing instantOS and booting into the new system on installer initiated reboot, the nerdfont glyphs in st did not render correctly. I did a fc-cache and rebooted and fonts work fine now.

**To Reproduce**
1. Install instantos from live usb
2. Wait for the installer initiated reboot
3. When booted into the new system, glyphs wont render

**Expected behavior**
Nerdfonts should work out of the box

**Relevant hardware**
 - NVidia 2070 SUPER
 - AMD Ryzen 3600

**Driver**
Nvidia proprietary as suggested by installer (v450)

**Additional context**
I suggest not putting too much effort into this yet, as i understand it might be hard to debug and an edge case on my system. Since i have it working there is no pressure or hurry from me, but if it happens more often people could reference this ticket and that might be a good trigger to put work into this issue or not.

Thanks!

**Comment by paperbenni** [comment]
This was only on the first reboot right? Did it go away after rebooting?

**Comment by RobertLemmens** [comment]
@paperbenni correct, only on first reboot. Worked fine after rebooting a second time.

**Comment by paperbenni** [comment]
Oh sorry, it even says so in the issue...
This is probably a locale issue, I think a temporary solution might be to just reboot a second time after applying the language settings
