### ISSUE TITLE
OS configurability

### ISSUE THREAD

**Issue by robcsi** [instantOS/instantOS#66]
**Ability to change aspects of the OS and the helper tools**
 - On a small screen the text sizes are too big. I'm using the OS on a 14" Thinkpad screen and the instantsettings, the status bar, dmenu, instantAssist and other similar tools provided have too large text size for my liking. GTK app font size can be reduced, so that's good
 - st font size
 - There are no gaps between the windows, which would probably be preferred by many (although considered useless by others). I would like to have configurable gaps
 - The shortcuts would be nice if were configurable. I changed many of them, because I'm used to having those

**A way to change these via the settings gui or central config file(s)**
As is it now, I have to dig into the instantWM source code as well as other places to changes these values, recompile, etc., a process which is not for everyone, having in mind that the motto is being friendly and not suckless (so no need for recompiling) to non-techies as well. 
I also digged into the instant* scripts and tools sources to change some font sizes and heights, but not all seem to work, or the whole look becomes inconsistent.

**Additional context**
Personally, I would be happy with having some config file(s) for changing these settings, but non-techies will probably want to have easier customization possibilities, similar to the GTK Appearance settings.

P.S.: I understand it's still a beta, and that's not a problem. Maybe some priority can be given to this aspect, too.

Keep up the good work, I like it a lot so far. I'm using it a daily driver now.

**Comment by con-f-use** [comment]
Please have a look at the [todo page](https://github.com/instantOS/instantOS/projects/1). Most of quarrels are already scheduled.

**Comment by robcsi** [comment]
St font size is not permanent after changing via shortcuts.

**Comment by con-f-use** [comment]
Agreed, and most of these are already on the ToDo.

**Comment by robcsi** [comment]
I'll take a better look next time, too. Thanks for the links.

**Comment by paperbenni** [comment]
Most of that stuff is already on the todo.
As for changing font size, there already is a dpi setting, you can go into settings->display->dpi
No need to edit the source code for that
