### ISSUE TITLE
How to copy/paste in terminal?

### ISSUE THREAD

**Issue by forkthat** [instantOS/instantOS#68]
**Describe the bug**
It may not be a bug (maybe I am missing something), but here goes.
Whenever I use Ctrl + Shift + C/V (as most terminals do) to copy/paste to and from a browser or text file, it doesn't work.
Also, when highlighting the wanted words to be copied, the highlight instantly vanishes the moment you release the mouse button.

**To Reproduce**
1. Open a terminal using Super + Enter
2. Do some stuff like neofetch, etc.
3. Highlight words.
4. Use Ctrl + Shift + C/V to copy/paste.
5. See error on steps 3 & 4.

**Expected behavior**
You go to the terminal and highlight the words you want.  Then you can copy/paste stuff using Ctrl + Shift + C/V.

**Screenshots**
N/A

**Device (only relevant in some cases):**
 - GPU: Radeon Vega 8 Graphics + Radeon 535 Graphics
 - CPU: Ryzen 5 2500U
 - Manufacturer/Model if prebuilt of laptop (e.g. Thinkpad, macbook 2015 etc):  Acer Aspire A315-41G-R4BW (laptop)

**Additional context**
I have noticed that some options appear when right-clicking on the terminal.  There were options such as copy, horizontal/vertical split, etc.  I tried to use the copy option but to no avail.

**Comment by paperbenni** [comment]
You need to highlight words using shift + left click, left click gets passed on to tmux or the application you're using

**Comment by forkthat** [comment]
Oh, okay.  Thanks!
