### ISSUE TITLE
instant os select keyboard layout no dutch(netherlands) and no belgian(dutch)

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantOS#7]
Hello.
so the select keyboard layout doesn't contain Belgian(period,dutch), Belgian(french) and dutch (Netherlands).
belgian(period, dutch) http://kbdlayout.info/kbdbe
blgian(frensh) http://kbdlayout.info/KBDBE/
dutch http://kbdlayout.info/kbdne

**Comment by paperbenni** [comment]
I now added Dutch and Belgian to the keyboard selection menu. More layouts have been added under "other" where you can select a layout by directly typing in its xorg name.

**Comment by NicTanghe** [comment]
this ws fixed
