### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by robinsrk** [instantOS/instantOS#70]
there is no support for Bangla font. Don't know about other fonts, but found no Bangla font installed in this distro. Please add Bangla font support...

**Comment by Titaniumtown** [comment]
Is this the "bangla" font you're speaking about? https://aur.archlinux.org/packages/ttf-freebanglafont/

If so, you can just install it from the AUR, because it doesn't seem that Arch Linux has it in their repos.

**Comment by robinsrk** [comment]
Sorry i am noob in linux. Learning it slowly slowly and that's why i don't
know much about it. Gonna give it a try again today, and thanks for your
response

**Comment by con-f-use** [comment]
Closed for inactivity.
