### ISSUE TITLE
Option on install to change <super> to Alt

### ISSUE THREAD

**Issue by blixuk** [instantOS/instantOS#72]
Would it be possible to have an option to change the <super> key to Alt on install?
I'm using a IBM Model M, this keyboard had no physical Win key.

**Comment by con-f-use** [comment]
@paperbenni is reworking keyboard bindigs. He'll probably include that option. In the mean time, if you compile instantWM from source, you can change that in config.h

**Comment by blixuk** [comment]
Ok, thank you.
