### ISSUE TITLE
Stutter / Freezes in CS:GO

### ISSUE THREAD

**Issue by DiXN** [instantOS/instantOS#74]
**Describe the bug**
Every 10 seconds the game stutters / freezes for about a second. In this period the mouse is unresponsive and even the sound can cut out.

**To Reproduce**
1. Start CS:GO
2. Join a match or move the mouse in the menu

**Expected behavior**
Moving the mouse exhibits stutter every 10 seconds.

**Device (only relevant in some cases):**
 - GPU: GTX 1070 
 - CPU: i7 8700k

**Additional context**
The same behavior can be observed running the original Counter Strike. In both cases every 10 seconds a very destinctive stutter can be felt and also in both cases right afterwards the process: 
 ```/usr/lib/Xorg :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch```
spikes in CPU usage from about 4% to 12% for a couple of seconds and then it goes back to its original state.

 I also do not know if this is even a problem specific to instantOS or if Xorg has anything to do with it. Momentarily higher CPU usage of Xorg is just the only real pattern I could observe while testing this.

**Comment by con-f-use** [comment]
Probably related: https://github.com/instantOS/instantWM/issues/23

**Comment by paperbenni** [comment]
Yes, that's also what I thought. I'll look into it

**Comment by DiXN** [comment]
It seems to be the exact same problem as in instantOS/instantWM#23.

I can also solve the problem by removing the check for display changes.

**Comment by con-f-use** [comment]
Closed as duplicate.
