### ISSUE TITLE
Can't save mouse reversal (invert) setting

### ISSUE THREAD

**Issue by letieu** [instantOS/instantOS#75]
1. I have set reverse scroll mouse for use touchpad , but when next time startup, it not effect 
2. My laptop audio not work, both headphone and speaker

**Device :**
 - GPU: intel graphics 520
 - CPU: i5 6300
 - Model: Dell latitude 7480

**Comment by paperbenni** [comment]
Does the status bar in the top right display the date and audio or is it empty/saying instantOS-beta?

**Comment by letieu** [comment]
> Does the status bar in the top right display the date and audio or is it empty/saying instantOS-beta?

I know why my audio not work, when press  FN + mute , end then pulseu audio is set mute, then FN + mute or FN volume  not work , so I need set back by pluseuAudio,

**Comment by con-f-use** [comment]
I seem to recall other people reporting the audio issue and that it might be fixed. So let's make this issue about about remembering inverted scrolling! You can open a separate issue for the audio if it persists after the next beta release.
