### ISSUE TITLE
Add "set time automatically" to system settings

### ISSUE THREAD

**Issue by ppenguin** [instantOS/instantOS#83]
**Is your feature request related to a problem? Please describe.**

Default is manual time setting and no way to choose "automatic" from `settings > Time and Date`

**Describe the solution you'd like**

Option "automatic" which enables and starts `systemd-timesyncd`

**Comment by paperbenni** [comment]
I recently [implemeted](https://github.com/instantOS/instantSETTINGS/commit/be781f790e3efb36a4e58b2e185350117e3db752) this in a [live stream](https://www.youtube.com/watch?v=6hGgHORwtY0)
