### ISSUE TITLE
mirror location in installer

### ISSUE THREAD

**Issue by hen6003** [instantOS/instantOS#84]
In the installer when choosing the mirror location, 'United Kingdom' and 'United States' is shown on two lines rather than one

**Comment by con-f-use** [comment]
Huh, do you men on one line rather than two? So, the other way around.

**Comment by paperbenni** [comment]
I know what you mean, difficult to explain xD

**Comment by paperbenni** [comment]
Ok, it should be fixed now

**Comment by paperbenni** [comment]
Issue is gone in a recent vbox test install, closing this...
