### ISSUE TITLE
Laptop keyboard key Mute only mutes

### ISSUE THREAD

**Issue by djongepier** [instantOS/instantOS#86]
**Describe the bug**
The keyboard has a "Mute" key, and the sound does mute when pressed, but it does not "toggle" or un-mute when pressed again.

**To Reproduce**
1. Press "fn + Mute (F1)"
2. Result: 
![20201228094016](https://user-images.githubusercontent.com/57892671/103202741-89bc3d80-48f3-11eb-9548-d78a0bcd871e.png)
4. This does not change, even with adjusting volume, it never becomes un-muted.

**Expected behavior**
If I press mute and then mute again, I expect it to become unmuted.

**Screenshots**
Made the screenshot inline.

**Device (only relevant in some cases):**
Laptop make and model: Starlabs Labtop MK IV
Keyboard: US

**Additional context**

**Comment by paperbenni** [comment]
I think I fixed this in master a while ago. Try installing instantASSIST from source (see [this](https://instantos.io/development/development)) and see if the issue persists. 
(the newer instantASSIST might be using some new instantMENU features as well so better install that from source as well)

**Comment by djongepier** [comment]
Hi Paperbenni,

You are correct, after installing from source with the ibuild tool the problem is no longer there. I did install both InstantMENU en instantASSIST.

Greetings,

Daniel
