### ISSUE TITLE
weird gui error ?

### ISSUE THREAD

**Issue by NicTanghe** [instantOS/instantOS#9]
hello descr is picture
![guierror](https://user-images.githubusercontent.com/13624265/82093930-6219bb80-96fc-11ea-90a7-6b0fbb43c930.png)

**Comment by NicTanghe** [comment]
also it's gone now after making a new window.

**Comment by paperbenni** [comment]
I don't see the error here. Can you describe what the problem is?

**Comment by paperbenni** [comment]
Do you mean the gap below the terminal? The terminal resizes in rows and columns, it does that on most distros actually.

**Comment by NicTanghe** [comment]
i mean the gap yes. 
There is only 2 windows open side by side .
only 1 has a gap and only at the bottom.

**Comment by paperbenni** [comment]
Yes, and it's the terminal. The gap doesn't fit an entire line of text so the terminal doesn't use that space. This is only the terminal, other applications use all the space available.

**Comment by NicTanghe** [comment]
then zhy does it only happen sometimes amd not all the time or answer doesn't make sense to me

**Comment by paperbenni** [comment]
Can you repeat that without spelling mistakes in every second word, I didn't understand that either. It's ONLY the terminal, and the terminal wouldn't be able to make use of that space since it doesn't fit a whole character.

**Comment by paperbenni** [comment]
It now ships with st which can take on any size, which fixes this.
