### ISSUE TITLE
instantmenu should use ~/.Xresources for e.g. font settings

### ISSUE THREAD

**Issue by ppenguin** [instantOS/instantOS#91]
**Is your feature request related to a problem? Please describe.**

Related to the inability to override defaults (e.g. font size), see also #90 

**Describe the solution you'd like**

Since `instantmenu` is based on `dmenu` (has the same `WM_CLASS`), propose to use this functionality https://tools.suckless.org/dmenu/patches/xresources/dmenu-xresources-4.9.diff also for `instantmenu`, thereby enabling configuring its appearance with `dmenu.*` in `~/.Xresources`.

**Comment by ppenguin** [comment]
This would be solved by PR https://github.com/instantOS/instantMENU/pull/9

**Comment by con-f-use** [comment]
This repo is also not the right place for it, closing this in favor of the aforementioned PR.
